### ISSUE TITLE
Survey copy

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/connect5#10]
@elysabethc5 do you think you'd be able to send us the copy for the surveys please? Ideally a word doc of sorts with the questions and options for each. 

Thanks!

**Comment by elysabethc5** [comment]
[Pre-course SurveyMonkey_151565181.pdf](https://github.com/techforbetter/connect5/files/2565220/Pre-course.SurveyMonkey_151565181.pdf)
[Session 1 SurveyMonkey_151558050.pdf](https://github.com/techforbetter/connect5/files/2565221/Session.1.SurveyMonkey_151558050.pdf)
[Session 2 SurveyMonkey_151565777.pdf](https://github.com/techforbetter/connect5/files/2565222/Session.2.SurveyMonkey_151565777.pdf)
[Session 3 SurveyMonkey_151566900.pdf](https://github.com/techforbetter/connect5/files/2565223/Session.3.SurveyMonkey_151566900.pdf)
 just a word of warning , im meeting with amnchester university 19th nov to revise  questions but for now this is what we are using 
thanks

**Comment by thejoefriel** [comment]
Perfect thanks very much!

**Comment by elysabethc5** [comment]
I’m not getting though , what do I need to do?

elysabeth Williams
National Connect 5 project manager
ewilliams@rsph.org.uk<mailto:ewilliams@rsph.org.uk>
Mobile: 07341 733 077

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorised. The sender does not accept liability for any errors or omissions in the contents of this message which arise as a result of email transmission. If you are not the intended recipient, any disclosure, copying, distribution or any action to be taken in reliance on it, is prohibited and may be unlawful.

The Royal Society for Public Health (RSPH) is a company incorporated by Royal Charter; reg no RC000825. It is also a registered charity; reg no 1125949

**Comment by elysabethc5** [comment]
Looks like my firewall is blocking it

elysabeth Williams
National Connect 5 project manager
ewilliams@rsph.org.uk<mailto:ewilliams@rsph.org.uk>
Mobile: 07341 733 077

The information in this e-mail is confidential and may be legally privileged. It is intended solely for the addressee. Access to this e-mail by anyone else is unauthorised. The sender does not accept liability for any errors or omissions in the contents of this message which arise as a result of email transmission. If you are not the intended recipient, any disclosure, copying, distribution or any action to be taken in reliance on it, is prohibited and may be unlawful.

The Royal Society for Public Health (RSPH) is a company incorporated by Royal Charter; reg no RC000825. It is also a registered charity; reg no 1125949
