### ISSUE TITLE
Agree on Database Schema Modification

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#162]
Think about how we can extend our current Schema so that ...
- trainers
- local leads as super user
- admin
- User PINs for surveys
- Attendee's emails for session
- new types of surveys (train the trainer, 2 day intensive..)
- new sets of questions (now having unique codes for calculation)
- new sets of answers (some as base for formulae)

all find their place.....

**Comment by RamyAlshurafa** [comment]
```js
const userSchema = new Schema({
  // email for login for [trainers, local lead, aadmi]
  email: {
    type: String,
    unique: true,
  },
  password: String,
  // the trainer's local lead
  localLead: {
    type: Schema.Types.ObjectId,
    ref: "users",
  },
  region: {
    type: String,
    enum: ["south east", "south west", "north east"], // what else??
  },
  role: {
    type: String,
    enum: ["admin", "localLead", "trainer"], // regional lead to be added
  },
  // name - to be showed in the dashboard
  name: String,
  organization: String,
});

// all [email, password, role, name]
// trainer all + [localLead, region, org]
// localLead all + [region, org]
```

**Comment by RamyAlshurafa** [comment]
### questions

```js
const questionSchema = new Schema({
  text: {
    type: String,
    required: true,
  },
  code: {
    type: String,
    required: true,
  },
  // the general group
  // [ "ABOUT YOU", "ABOUT YOUR TRAINER", "ABOUT YOUR USUAL WAY OF TEACHING"]
  group: String,

  // sub groups
  // ["Did your trainer ask questions...", "Did your trainer...", ...]
  subGroup: {
    text: String,
    order: Number,
  },

  // array of strings e.g [""pre-day-1", "post-day-1"]
  // the same question maybe will be in multiple survey
  // or do we need to repeat them for each question ???
  surveyType: [{
    type: String,
    enum: ["pre-day-1", "post-day-1", "post-day-2", "post-day-3", "post-special", "pre-train-trainers", "post-train-trainers", "follow-up-3-month", "follow-up-6-month"], // ....
  }],
  answerType: {
    type: String,
    enum: ["number", "yes/no"],
  },
  helperText: String, // do we need it ????
});
```

**Comment by RamyAlshurafa** [comment]
### Responses

```js
const sessionSchema = new Schema({
  date: {
    type: Date,
    default: Date.now(),
  },
  type: {
    type: String,
    enum: ["1", "2", "3", "special-2-days", "train-trainers"],
  },
  // trainer need to enter it, as the exist
  // do we need to calculate it from the number of attendees email ???
  numberOfAttendees: Number,
  region: {
    type: String,
    enum: ["south east", "south west", "north east"], // what else??
  },
  // array of trainers must be 2 max
  trainers: [{
    type: Schema.Types.ObjectId,
    ref: "users",
  }],
  // list of participants emails
  participantsEmails: [String],
});
```

**Comment by RamyAlshurafa** [comment]
### Responses
```js
const responseSchema = new Schema({
  // Respondent PIN
  // what if the respondant was a trainer for trainer the trainers sessions
  userPin: String,
  // can be trainer or local lead
  // who led the senssion
  trainer: {
    type: Schema.Types.ObjectId,
    ref: "users",
  },
  surveyType: [{
    type: String,
    enum: ["pre-day-1", "post-day-1", "post-day-2", "post-day-3", "post-special", "pre-train-trainers", "post-train-trainers", "follow-up-3-month", "follow-up-6-month"], // ....
  }],

  // for what session 3-months & 6-months surveys will be associated ???
  // or do we need to make survey collection,
  // then the responses will be associated for the surveys not sessions ???
  session: {
    type: Schema.Types.ObjectId,
    ref: "sessions",
  },
});
```

**Comment by RamyAlshurafa** [comment]
### behavioral insight

```js
const behavioralWords = new Schema({
  text: String,
  // ["In the last week ...", "Your behavior is influenced by your..."]
  group: {
    type: String,
  },
});

const behavioralValues = new Schema({
  // participant PIN
  PIN: String,
  behavioralWords: {
    type: Schema.Types.ObjectId,
    ref: "behavioralWords",
  },
  value: Number,
  type: {
    type: String,
    enum: ["percentage", "figure"],
  },
});
```

**Comment by thejoefriel** [comment]
In questions you're right @RamyAlshurafa that a question could be for more than one survey. Is the simplest way to do this that the type is an array? And then we can store in the array all of the surveys that question is for? Would that work?

```
// array of strings e.g [""pre-day-1", "post-day-1"]
  // the same question maybe will be in multiple survey
  // or do we need to repeat them for each question ???
  surveyType: [{
    type: String,
    enum: ["pre-day-1", "post-day-1", "post-day-2", "post-day-3", "post-special", "pre-train-trainers", "post-train-trainers", "follow-up-3-month", "follow-up-6-month"], // ....
  }],
```

Also could we change answerType to questionType? I think this is clearer.

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa I noticed we haven't got an Answers model here. Is that because it's just going to be the same as the one we created for sprint 1?

**Comment by thejoefriel** [comment]
@RamyAlshurafa - can you talk through the logic and reasoning for the Behavioural Insight please?

**Comment by thejoefriel** [comment]
Replies to your other questions as well @RamyAlshurafa :
```
enum: ["south east", "south west", "north east"], // what else??
```
Total list of regions to include are on this pdf: file:///Users/joefriel/Documents/Joe/Work/Connect%205/Pre-course.SurveyMonkey_151565181.pdf

```
helperText: String, // do we need it ????
```
Looking at the questions we don't seem to use it currently so can remove, but equally fine to leave in as may be useful in future

```
// do we need to calculate it from the number of attendees email ???
  numberOfAttendees: Number,
```
No, this would only be based on the number that the trainer puts into the attendee field when adding/editing a session because they may not want to add emails to the session details 

```
// for what session 3-months & 6-months surveys will be associated ???
  // or do we need to make survey collection,
  // then the responses will be associated for the surveys not sessions ???
```
Interesting question. Technically participants do not need (or would want) to attend all three sessions. It might be that only they attend session 1 and 2. So technically whenever the trainer creates a new session we should generate 3-month and 6-month survey links. So I guess the survey would be linked to whichever session it was created for?  Arguably this could mean participants who attend multiple sessions getting quite a lot of follow up surveys, but maybe the simplest for now and we can review with Elysabeth. @dupreesi and @elysabethc5 - what do you think on this?

```
// what if the respondant was a trainer for trainer the trainers sessions
  PIN: String,
```
If the respondent is a trainer doesn't matter. We would still expect them to enter a PIN so we can make their feedback anonymous - in that way they are just like any other participant.

**Comment by RamyAlshurafa** [comment]
@thejoefriel sorry for the delay
for the behavioural insight, we have 2 tables:  
"behavioralWords" (not sure if this the right naming for it) and this will store the sentence words to be showed in the UI (eg. You suggested to [insert percentage] of people who needed it,  ways they could take action on their own mental health or wellbeing)

and "behavioralValues" to store the value that calculated using the formulae. and will link each value with the "behavioralWords"

**Comment by dupreesi** [comment]
@thejoefriel I agree on this. Lets create follow up survey links for each session. we can refactor this in future. in future maybe we can check what the last session a participant attended was and then only take those follow up surveys.

**Comment by dupreesi** [comment]
@RamyAlshurafa sounds good to me

**Comment by thejoefriel** [comment]
Hey @ramyalshurafa I'm not sure this behavioural insights works at the moment? If we're storing these values separately then we need to store the survey and session those values have been calculated for? Otherwise there's no way of showing the breakdown per session or filtering to show the relevant ones for that trainer or local lead?

**Comment by RamyAlshurafa** [comment]
yeah, you are right I will fix that
