### ISSUE TITLE
Agree on tech stack and eslint

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#170]
I guess we're keeping the Mongo Express React combo and will include Redux

**Comment by thejoefriel** [comment]
Yes totally agreed on this @dupreesi  and following on from our chat this morning we will use thunk for redux async stuff

Also random thoughts on other packages:
**Front**
- Styled Components (no need for Tachyons either - and would be good to set up similar to the earwig project with a theme.js)
- react-select - used before and most useful for adding attendee list etc
- sweetalert2 - easy to use and we've all used this now
- Let's make sure we don't use SVG package but instead set up our own Icon common component to manipulate the SVGs
- I don't mind whether we use Formik or not although felt that caused more problems than it solved on our other project - what do you think @amusameh ?

**Back**
- Open on whether we use Passport or create our own authentication middleware
- happy with boom or http-errors. Perhaps boom is slightly better but not too fussed

**Comment by dupreesi** [comment]
@thejoefriel in case we are using redux @marwajomaa suggested redux-form which is apparently quite straightforward...

**Comment by amusameh** [comment]
Are we using a components library like ant desgin which will make doing a lot of thing easier like the collapsed tabs?
What do you think?  @dupreesi @thejoefriel @RamyAlshurafa
