### ISSUE TITLE
Trainer: Behavioural Analysis for individual session

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#179]
relates #174 
**front-end**
- [ ] render intro text, feedback text and results for that session (categorising participants ranking outcomes related to one session) as bar charts

**back-end** 
- [ ] query: aggregate individual behavioural results by session id, calculate percentages categorised by ranking outcomes (0-20, 21-40, 41-60, 61-80, 81-100)
- [ ] controller: send results to session detail page for trainer
<img width="213" alt="Bildschirmfoto 2019-05-11 um 12 02 09" src="https://user-images.githubusercontent.com/23721486/57568232-a76a2580-73e4-11e9-86a9-ce2c3dbec017.png">

**Comment by RamyAlshurafa** [comment]
@dupreesi @thejoefriel 
this is `formulae for feedback to trainer`  section in the doc from the resources? it's empty how to calculate it?
for now, we have the `formulae for feedback to user level`
so maybe this is the aggregated for all users results?
