### ISSUE TITLE
Set up formulae for user responses

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#181]
Let's discuss this: 
--> relates update of survey #208 
we need to show behavioural insight functions for multiple pages, always counted in different ways
- [ ] the trainer results page (all participants related to 1 trainer, categorised by session type)
- [ ] the session details page (all participants related to 1 session) 
- [ ] the local lead group results page (all participants related to all sessions within group categorised by session type)
- [ ] the admin overall results page (all participants categorised by session type)

--> set up re-usable functions that calculate 1 participant's behavioural insights by getting relevant questions/ answers of that individual, using the formulae provided

**Comment by RamyAlshurafa** [comment]
@dupreesi 
>the local lead group results page (all participants related to all sessions within group categorised by session type)

for the local lead, the behavioural insight will be calculated from `users` that attend sessions within the group? so his/her trainers' participants?
or it will be the participants they attend his/her session directly?

**Comment by dupreesi** [comment]
@RamyAlshurafa check figma again -> there is now a tab that switches between My Results and Group Results. Sorry forgot to add this
