### ISSUE TITLE
common components issue

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#183]
list here common component ideas

**Comment by dupreesi** [comment]
- [ ] navbar (different for across all users)
- [ ] behavioural insights 
- [ ] trainer feedback
- [ ] dashboard

**Comment by thejoefriel** [comment]
Hey I've gone through Figma and worked out a number of bits we can turn into common components. This is also building on what @dupreesi has written above:

- [ ] Results Section folder
	- [ ] Behavioural Analysis
	- [ ] Trainer Feedback
	- [ ] Reach

- [ ] Toggle (e.g. Group Results | Individual Results)

- [ ] Navbar

- [ ] Lists folder
	- [ ] Sessions
	- [ ] Trainers

- [ ] Headers folder
	- [ ] Section Header (e.g. Trainer)
	- [ ] ViewHeader (e.g. Viewing John Doe)

- [ ] Buttons
	- [ ] Light Button
	- [ ] Dark Button

- [ ] Info bubble (e.g. John Doe info)

 - [ ] Routes folder
	- [ ] Private
	- [ ] Public

Dashboard can actually just be a page as it's the same for all users, just showing different info in the sections based on the type of user

I've grouped up all the pages in the All screen on figma so you can also see where we can use the same type of page across all/multiple users: https://www.figma.com/file/FSYdqP87hx39PwGA74OhkKmu/Connect-5?node-id=702%3A0
