### ISSUE TITLE
Update Authentication System

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#207]
- [ ] roles: participant (level 1), trainer (level 2), local lead (level 3), admin (level 4)
- [ ] cookie management instead of local storage (?) 
- [ ] Redux Storage instead of React App State

**Comment by thejoefriel** [comment]
Think this makes sense. Is there a separate issue for setting this up? If not, now we've discussed this in our chats @dupreesi  maybe we should remove the assignees so whoever takes this on can assign themselves and it's clear who's working on this?

**Comment by dupreesi** [comment]
@thejoefriel there are separate issues related to this all labeled auth
so I'm closing this issue now
