### ISSUE TITLE
Update Surveys

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#208]
Please have a look at the resource issue #161 -> C5 Evaluation questions and Demographic questions

**formats** 
- [ ] Pre-course day 1
- [ ] Post-course day 1
- [ ] Post-course day 2
- [ ] Post-course day 3
- [ ] Post special 2-day course
- [ ] Pre train the trainer 
- [ ] Post train the trainer
- [ ] 3 month follow-up
- [ ] 6 month follow-up

**sections**
- [ ] Insert PIN -> Required to track survey results to participants
- [ ] Demographic questions --> important for data collection
- [ ] About You --> leads to behavioural insights  
- [ ] About Your Trainer --> leads to trainer feedback 
- [ ] About your usual way of teaching --> leads to train the trainer feedback

**Comment by RamyAlshurafa** [comment]
@dupreesi 
`Demographic questions` in the document doesn't contain question it contains the PIN formula
need to be updated?
