### ISSUE TITLE
Suggestion: only use redux-devtools-extension in development

### ISSUE THREAD

**Issue by tyeung2017** [yalla-coop/connect5#222]
I dont think it is a good idea to use it in production at all, let alone only in production.

I personally would only use it as dev tool to debug; you can dynamically import it when running dev mode, so that the bundle size can be smaller

**Comment by amusameh** [comment]
thanks @tyeung2017 
I updated the store config to only use devtools on the development. please take a look.

I based my store config on this article which recommend using a minimal version for logs only. which is what that import is doing => it runs full devtools on development and a minimal version of it on the production . I mean it's still using the browser devtools extension.
https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

This is just a helper for the hooking the store with the browser extension. 
https://www.npmjs.com/package/redux-devtools-extension

What do you think about this? If you could direct me on how do you structure your store?

**Comment by tyeung2017** [comment]
I would say try to keep the store as simple as possible; you can always add things afterwards

depending on the need, you may even not need a devtool to log if the redux logic is simple enough

to me the devtool is only for debugging, and I definitely dont want it to be in production.

the dynamic import thing, you can refer to this: 

https://github.com/wesbos/Learn-Redux-Starter-Files/blob/master/19/store.js

of course, dont copy it, as you dont really need all those redux hot reloading features now; try to understand it
