### ISSUE TITLE
As a trainer I want to get a dashboard on the platform, So I can get some actions.

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#28]
## As a trainer I want to get a dashboard on the platform, So I can get some actions.
Relates #24 
 #### Acceptance criteria:
- [ ] When I'm on "dashboard" page, I want to be a to see a welcome message, with my name.
- [ ] When I'm on "dashboard" page, I want to get some statistics on my sessions.
- [ ] When I'm on "dashboard" page, I want to be able to navigate through the dashboard parts ( Add, Sessions, Results )
- [ ] When I'm on "dashboard" I want to see a header that contains a button to redirect me the "Landing" page.

**Comment by thejoefriel** [comment]
This will be for the second sprint when we build out sections other than "Sessions". For the first sprint, once the trainer logs in, they can be taken to the "View Sessions" page instead.
