### ISSUE TITLE
Participant: After attending a session I can download the resources from that session on the app via my PIN log in

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/connect5#316]
PO to send across the resources that should be available after each session. Wireframe will then be created.

**Comment by RamyAlshurafa** [comment]
Is the resources would be variant for each session or they are static files? or the trainer will upload the files after each session?

**Comment by dupreesi** [comment]
@RamyAlshurafa they will be static files such as PDFs. can vary for each session

**Comment by dupreesi** [comment]
I will send the PO a reminder to send those across today

**Comment by RamyAlshurafa** [comment]
@dupreesi thanks
I will work on this, and when the PO send will add them later

**Comment by dupreesi** [comment]
perfect @RamyAlshurafa the email was sent yesterday

**Comment by RamyAlshurafa** [comment]
@dupreesi I logged into the `Connect 5` drive and I made a Folder for each session and shared the directory with the participants
so it's okay whenever the files ready they add them on the drive so no need to change the code as they are using the same folders I have created
