### ISSUE TITLE
Participant: After filling in the survey I am taken to my dashboard and get a pop up message saying "congratulations here is your certificate"

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/connect5#317]
I can choose to download the certificate, enter an email address for it to be sent to or 'Skip for now' to go to my dashboard

This can be a sweet alert pop up with a link to the certificate section of their dashboard

**Comment by dupreesi** [comment]
@RamyAlshurafa if pre-survey something like that 

Thanks for filling out the pre-session survey. To claim your certificate you will need to fill out the post-survey after the session.

**Comment by RamyAlshurafa** [comment]
@dupreesi Thanks :+1:
