### ISSUE TITLE
Participant: If I click a registration link I am taken to a page to confirm my email address and select confirm

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#324]
relates #323 

<img width="295" alt="Bildschirmfoto 2019-07-16 um 17 12 54" src="https://user-images.githubusercontent.com/23721486/61306499-05542880-a7ed-11e9-95e5-7cfd324de2b5.png">

**Comment by RamyAlshurafa** [comment]
@dupreesi What is the purpose of this step? should this be `Enter your password` instead of, like what Github does?

**Comment by dupreesi** [comment]
@RamyAlshurafa this would be the confirmation of someone attending the session. inputting the email would put them on the attendee list

**Comment by RamyAlshurafa** [comment]
@dupreesi so this is incorrect `Trainer & LocalLead:`  in the issue title? should be  `participant:`?

**Comment by dupreesi** [comment]
@RamyAlshurafa yes sorry thats wrong :)
