### ISSUE TITLE
Trainer & LocalLead: I can view a Manage Attendees section

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#325]
- Number of confirmed attendants
        - if someone confirms a registration link then this will increase the number
        - The trainer can also manually increase or decrease the number by updating the attendee list
    - View attendee list (same as invitee)
    - Add attendees (same as invitee list)
    - Send email reminder to attendees
        - this would be the session info mail containing survey links and details
    - View sent emails
        - same as for invitees

<img width="265" alt="Bildschirmfoto 2019-07-16 um 17 16 46" src="https://user-images.githubusercontent.com/23721486/61306888-9c20e500-a7ed-11e9-9a6d-530b7149079e.png">
<img width="271" alt="Bildschirmfoto 2019-07-16 um 17 16 57" src="https://user-images.githubusercontent.com/23721486/61306929-aa6f0100-a7ed-11e9-9873-9b7227cb98b3.png">
<img width="267" alt="Bildschirmfoto 2019-07-16 um 17 17 06" src="https://user-images.githubusercontent.com/23721486/61306933-b064e200-a7ed-11e9-8a11-8a9c3305e00f.png">
<img width="172" alt="Bildschirmfoto 2019-07-16 um 17 17 24" src="https://user-images.githubusercontent.com/23721486/61306948-b3f86900-a7ed-11e9-9c3c-85bcc8c3a65e.png">

**Comment by RamyAlshurafa** [comment]
@dupreesi 
`The trainer can also manually increase or decrease the number by updating the attendee list`
does that mean when trainer add attendee that will add them as participants in the db with `confirmed` status?

**Comment by RamyAlshurafa** [comment]
`View attendee list ` 
does that mean that I will filter the participants by `status = confirmed`?

**Comment by RamyAlshurafa** [comment]
```
 - View sent emails
    - same as for invitees
```
should this show the reminder emails? or show all email list?

**Comment by dupreesi** [comment]
@RamyAlshurafa 
yes - adding emails will insert new participant with confirmed status
yes - view attendees are all participants with status confirmed
sent emails - I would show all emails that are sent to participants with status confirmed - so that would be the initial email with the survey links and the reminder emails.

**Comment by RamyAlshurafa** [comment]
Sorry @dupreesi 
could you explain this 
`sent emails - I would show all emails that are sent to participants with status confirmed - so that would be the initial email with the survey links and the reminder emails.`

**Comment by dupreesi** [comment]
@RamyAlshurafa not sure actually. We could make 1 table for all session emails with an enum field describing the purpose like [invitation, invitationReminder, sessionInfo, sessionInfoReminder]? 
What do you think?

**Comment by RamyAlshurafa** [comment]
@dupreesi yeah that's true currently @marwajomaa added the emails into the session schema and stores the details of the email, but we still need to add that field to know the email purpose
