### ISSUE TITLE
User Testing Session Management July 31st

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#333]
Main question being: **Are we able to finish the major user stories** until then (< 2 weeks). 

The main user stories being the usage of the menu section (event details, invite & promote, manage attendees, get feedback).

If we feel that this would be too tight we can still do user testing but rather than managing the session we can focus on using the survey part of the app (the other set of user stories).

Please let me know what you think.

**Comment by thejoefriel** [comment]
Hey @dupreesi - I think we can finish the major user stories, but my concern is around bugs. I think 31st July would be very tight to ensure all of it could work. Would we be able to let them know closer to the time?
