### ISSUE TITLE
Refactor: disable the ability to update session type if there are responses on it

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#354]
changing the survey type when the session has some responses will cause a conflict since the old response will have answeres and question that are not related to the new session type.
So I think that on edit page we should check if the session has responses then we should disable the type input

**Comment by RamyAlshurafa** [comment]
@dupreesi 
What do you think about this? Am I correct?

**Comment by dupreesi** [comment]
@RamyAlshurafa sorry I've just seen this :( did you disable it? i think it'd be good!

**Comment by RamyAlshurafa** [comment]
I will start working on this now
