### ISSUE TITLE
Bug: participant - show header with home button

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#358]

**Comment by amusameh** [comment]
@dupreesi 
You mean delete the header that display (My progress) and replace it with normal header with home icon

**Comment by dupreesi** [comment]
@amusameh up to :) you could maybe just integrate home/dashboard and connect5 (/) buttons into the current one or just use the common component

**Comment by dupreesi** [comment]
just about giving an option for the user to get back to dashboard and the landing page

**Comment by amusameh** [comment]
@dupreesi  I just added the header with the home button. which will redirect to participant dashboard

**Comment by dupreesi** [comment]
perfect
