### ISSUE TITLE
refactor Local lead sessions query

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#373]
user story: as a local lead I see all sessions that are related to trainers of my group. 
currently a local lead can only see sessions where he/she is registered as a partner or second trainer

**Comment by RamyAlshurafa** [comment]
@dupreesi sorry I was wrong,
@amusameh did this and it's getting the all the sessions for the local lead and the group

**Comment by dupreesi** [comment]
@RamyAlshurafa @amusameh in production when logged in as a local lead and setting up a session without putting partner trainers in (local lead = trainer) the session is not getting added to the sessions table of that local lead 
https://www.loom.com/share/285b61b89b8b418f9a59ee694983f307
