### ISSUE TITLE
Dashboard: Add headline above stats

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#461]
"Your Total Reach" 
this is to make sure they understand that the stats are overall results

**Comment by marwajomaa** [comment]
Hey @dupreesi  
do you mean to add  "Your Total Reach" above this container 
![Screenshot from 2019-08-25 11-50-35](https://user-images.githubusercontent.com/34250163/63647759-cb047200-c72e-11e9-86a1-d626c0cc6266.png)

**Comment by dupreesi** [comment]
@marwajomaa yes thats it!
