### ISSUE TITLE
Bugs when adding an already registered trainer to group

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#505]
video: 
https://www.loom.com/share/062d901777d74ec6aa637ef875457178

**Bugs spotted:** 
- when adding a registered trainer to my group => email gets send twice (also pop up opens twice)
- this also holds when registering a new trainer!
- each email contains different password
- email is missing link to register/ login
- email doesn't render trainer name (undefined)
- email doesn't render local lead name (region) correctly -> name of local lead should be capital and region put in (region), e.g. Martin (North-East)
- password(s) in email(s) don't work for already registered trainer -> old password still works

**Proceedure:** 
- when adding a new trainer to group -> send email with password including link to login -> permission successful
- when adding a trainer that's registered -> don't send email and allow permission as every trainer needs to check permission confirmation box when signing up!

**Comment by RamyAlshurafa** [comment]
@dupreesi 
I think the process of adding a registered trainer to the group need to be changed to:
when local lead inputs a registered trainer's email,

1. it should remove the trainer from his old local lead group
2. add him to the new local lead group
3. reset access permission for the trainer to be false again. so the new local lead can't see the trainer results.

4. send him an email (without sending a password and with another body) like `<local lead> added ou to his/her group ... for now <local lead> can't see your results, and by processing, you'll give him access permission to your result,.... contact us if you have any issue or conservation....`
5. when trainer log in then update `access permission` to be true

in this way, we aren't reseting the registered trainer password
what do you think? @dupreesi @thejoefriel

**Comment by dupreesi** [comment]
That sounds good to me! Great work ;)

RamyAlshurafa <notifications@github.com> schrieb am Mi., 4. Sep. 2019,
00:31:

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
What do you think about this?
and if you could word the email message it would be very good?
