### ISSUE TITLE
Update Trainer giving View Data Permission Flow

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#511]
We need to change the flow so that a local lead/ trainer manager does not have to wait for a trainer's permission when adding him/her to the group. We still need to give the trainer an option to deny permission because of data regulation laws.

**Changes required:** 

NEW (unregistered) Trainer gets added to trainer group by local lead/ trainer manager and Trainer receives following Email: 

Hi {Trainer Name}, 

{Trainer Manager/ Local Lead Name} ({Region Name}) has added you to his/her group as a trainer. 

You can now log in at {URL} using the following credentials: 

account name: {email}
password: {password}

Once logged in you can change your password.

Note: If you do not agree that {Trainer Manager/ Local Lead Name} can view your individual feedback data given by course participants please click the button underneath. If there appears to be an error please contact us directly. 

< BUTTON >
I don't want my trainer manager/ local lead to view my feedback data
</ BUTTON >

Thanks,
Connect 5

**Update Sign Up**
- update user model -> delete givenPermission attribute
- delete givenPermission related functions from frontend and backend

**Emailing function Changes:** 
- when trainer clicks button in email (see above) -> Post request to delete trainer from trainer group
- e.g. c5.training/remove/localLead_id:/ trainer_id:

**View Trainer Results Changes:** 
- view results button will always be visible -> remove check for givenPermission attribute
(now we delete the trainer from the group if no permission given)

**Comment by amusameh** [comment]
@dupreesi @thejoefriel  What should be the subject line for the email in the issue?
