### ISSUE TITLE
embed 3/6 month follow up survey flows

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#537]
- relevant sessions => all sessions 
- follow up survey contents: see database (main difference is between train the trainer and other session types)

- FLOW:
We stop at the highest level but include all levels below. So someone stopping at type 2 will still receive follow up question for types 1 and 2 but not type 3."
So every participant that completes a session relevant to follow-up surveys will receive 3 and 6 month follow-up surveys for this session.

- Tasks:
- [x] for each session: create category "Follow Up Survey Emails" (Section "Get Feedback)
- [x] for each session: create 2 scheduled emails including respective follow up link (need to be timed related to session date and send to all attendees)
- [x] show these 2 emails in the new section (like in the other schedule email sections)
- [ ] embed edit function (like in the other email sections)

- update codebase so these surveys are embedded
- create scheduled emails showing up in respective sections

**Comment by dupreesi** [comment]
Reply by Uni: 
"So we think that we stop at the highest level but include all levels below. So someone stopping at type 2 will still receive follow up question for types 1 and 2 but not type 3." 
This is certainly not the best UX but makes things easier for us. So every participant that completes a session relevant to follow-up surveys will receive 3 and 6 month follow-up surveys for this session. Sounds good?

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
In your PR #575
I saw you have added the follow-up surveys, but you used the same surveyType `follow-up-3/6-month` for [1,2,3,special-2-days] sessions and `follow-up-3/6-month-train-trainers` for TTT sessions with the same surveyTypes.

do you think it would be better to make a survey type for each session?
eg.
`follow-up-3-month-1` & `follow-up-6-month-1` for session `1`
`follow-up-3-month-2` & `follow-up-6-month-2` for session `2`
...

keeping the same name for multiple surveys I think it will break some queries that grouping base on surveyType and the query that check if the user filled the pre surveys or not

what do you think? @dupreesi @thejoefriel
