### ISSUE TITLE
change the Profile page => local lead section to be list of groups that trainer belong to

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#541]
the current profile page view your local lead as one field,
need to be updated to be a list of local leads and `remove` button to remove the trainer from that group

**Comment by dupreesi** [comment]
@RamyAlshurafa can you please explain this further? is this for the trainer profile? a trainer only ever got 1 official local lead and will never have the possibility to remove him/herself from any of his/her groups right?

**Comment by RamyAlshurafa** [comment]
@dupreesi 
you are right, but we agreed that the trainer can be in multiple groups, so we keep the existed functionality to select the official local lead, and add a table to show the trainers a list of groups that the trainers in, and he can leave/remove themselves from any group they want.
make sense?

**Comment by dupreesi** [comment]
@RamyAlshurafa have you already started working on this issue? if yes - please go ahead and finish but if not don't worry about this feature. In the end its the managers and/or local leads that add/remove trainers from their groups. but its a nice feature to have so all good if you're already working on this.

**Comment by RamyAlshurafa** [comment]
@dupreesi 
I didn't start working on this.
but I was thinking that when managers add the trainers to their groups then the trainers have the option to remove themselves from the groups that they added to.
so do you think that we should do this, or we have more priority issues to work on?

**Comment by dupreesi** [comment]
If you think this is important then please go ahead @RamyAlshurafa! 
If not, then let's put this as a bonus feature and start working on the remaining issues coming back to it when there is more time. 
What do you think?

**Comment by RamyAlshurafa** [comment]
for now, the link that sent to trainers to remove themselves from the group when they've been added to a group is not working.
so will update the profile page and make the functionality for the link together

**Comment by dupreesi** [comment]
cool sounds good!

**Comment by dupreesi** [comment]
@RamyAlshurafa I've pushed my PR and the link is working now....
