### ISSUE TITLE
Train the trainer formulae evaluation

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#569]
We’ve got 2 categories:
ABOUT YOUR USUAL WAY OF TEACHING (TRAIN THE TRAINER)
- for pre-tt survey 
- response format always 0 (strongly disagree) to 10 (strongly agree) 
 
ABOUT HOW YOU EXPECT TO TEACH IN THE FUTURE (TRAIN THE TRAINER) 
- for post-tt survey 
- response format varies between 0 (strongly disagree) to 10 (strongly agree) and not at all / a little / a lot / I'm not sure
 
Currently I cannot see any formulae provided for related question codes (we’ve only got formulae for trainer feedback categories)
 
Are you gonna provide us with those? 
 
**RESPONSE BY UNI:**
These don’t have formulae to add them together in any way.  
For the dashboard going back to individual trainers, people will want to see their own movement on each question from pre to post to follow up.  
For the dashboard for supertrainers, people will want to see the average (mean) of the trainers they are responsible for, again for each question.  

**Does that make sense?**

**Comment by thejoefriel** [comment]
For this one we would render the bar graphs fo each question with a bar for each of the ratings (0 to 5, so 6 bars in total)

**Comment by thejoefriel** [comment]
Since the Train the Trainer feedback is so different, I would suggest we have a separate section for this in the results page. So in total you'd have:

- Overall
- Trainer Feedback
- Train the Trainer Feedback
- Behavioural Insights

Train the Trainer would only be visible though for Local Leads and above
