### ISSUE TITLE
Responses not showing up in the Session Details page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/connect5#574]
In the feedback section it's showing 0 responses, but when you click through to results actually there are responses, they're just not being shown in the session details page. 

https://www.loom.com/share/0e96af98eac54bc9b5c3ce046156ab2e

**Comment by amusameh** [comment]
hey @thejoefriel  @dupreesi 

There are 2 responses from unconfirmed users here. so it shows 2 out of 0? 
should I keep it as it is? or do I need to change the number of attendees to something else? 

![Capture222223212](https://user-images.githubusercontent.com/28042978/65385341-668d0080-dd36-11e9-836c-01230d81e327.PNG)
