### ISSUE TITLE
If trainer edits local lead in profile section -> notify local lead via email

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#578]
Notify new local lead and old local lead: 

Dear {Local Lead Name},
Trainer {Trainer Name} has {removed?/ added?} you as their official Connect 5 local lead. 
If this doesn't seem correct please contact this trainer directly. 

Note: You can always edit trainer group management settings via the app.

Best wishes, 

Connect 5 team

**Comment by amusameh** [comment]
@dupreesi  Is this for official local leads or trainer mangers?
