### ISSUE TITLE
Create filter component 

### ISSUE THREAD

**Issue by marwajomaa** [yalla-coop/connect5#598]

**Comment by RamyAlshurafa** [comment]
Hey @marwajomaa 
are you going to work on this?
if so please take a look on this issue to know what filter data shape should be #597
my thoughts for this to be a common component that can be called in multiple places and multiple users levels
- can be used for behavioural insight, feedback results & train trainers results.

`props`:

1.  `role`: 
 - admin => can select localLeads & trainers + main filters
 - local lead => can select trainers + main filters
 - trainer => can select the main filters
2. `updateFilters` callback:
   to return the filters value in the parent component
3. `handleSubmit` callback:
  to handle submit the filters in the parent component
4. `clearFilters` callback:
  to reset filter values in the parent component
