### ISSUE TITLE
Survey Behavioural Insight Section: Embed Icon (i) with explanation

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#599]
- PO has sent over an explanation about the various categories of behavioural insights and a lin to a video URL. 
- Please put icon next to Headline of each survey that includes BI section. 
- Open Popup on click with text 
- embed video directly into popup if possible
- each Find out More section of the explanation document should be an expandable link/ drawer...
 
[Connect5Behaviours.docx](https://github.com/yalla-coop/connect5/files/3656263/Connect5Behaviours.docx)

**Comment by RamyAlshurafa** [comment]
Keep this open please until getting the video link from PO
