### ISSUE TITLE
Please Check: Server error when trying to register

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#631]
<img width="680" alt="Bildschirmfoto 2019-10-10 um 14 12 22" src="https://user-images.githubusercontent.com/23721486/66567690-100e2780-eb68-11e9-9840-26aad07ee277.png">

seems to throw errors because of survey types updates 
-> validation error because of invalid enums for follow up survey types in related controllers

**Comment by RamyAlshurafa** [comment]
will be fixed in #648
