### ISSUE TITLE
Bug: Participant Insights -> error page

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#652]
https://www.loom.com/share/5887b4ebd6514cd08535d6c1e43f5ed8

**Comment by RamyAlshurafa** [comment]
can you paste the error message you got in from console/terminal please, it works fine for me

**Comment by dupreesi** [comment]
oh ok I'll try again

**Comment by RamyAlshurafa** [comment]
@dupreesi 
did you check this?
