### ISSUE TITLE
what survey and sessions must be in the `Reach` section?

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/connect5#669]
in Figma, the reach section contains all the sessions and surveys even if the trainers haven't any session with 0 value for sessions and `N/A` for surveys,  and that what it was before,
![Screenshot from 2019-10-17 11-08-59](https://user-images.githubusercontent.com/34629478/66990632-43543780-f0cf-11e9-96c5-b84a3224aeb1.png)
-------------
-------------
now it just a list of the trainer sessions only
-------------
![Screenshot from 2019-10-17 11-15-01](https://user-images.githubusercontent.com/34629478/66990698-61219c80-f0cf-11e9-8ff8-80d850319251.png)

**Comment by dupreesi** [comment]
Does the current way make problems for filtering? Because I think it's ok to only see sessions that are actually being organised by the user and surveys that are related to those

**Comment by RamyAlshurafa** [comment]
Both ways don't make any issue to filters, what is the best?
@dupreesi

**Comment by dupreesi** [comment]
Ok then just keep it as it is please :)
