### ISSUE TITLE
BUG: Demographic section gets rendered for PINs that have already filled it out before

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#679]
Example: 
If I fill in the pre-survey for session 1 -> my PIN gets stored in participant table
If I use this PIN to fill in the pre-TTT -> demographic section should be filtered out of unique groups array by  action GET_PARTICIPANT_BY_PIN_SUCCESS. The action gets called twice and overrides the first filter...

**Comment by RamyAlshurafa** [comment]
@dupreesi 
I went through the steps you wrote above and it didn't show me the demographic questions in the second time

**Comment by RamyAlshurafa** [comment]
ah sorry, you are right this solved in the fx-bigs-s5 PR
