### ISSUE TITLE
Bug: Participants on Dashboard seem to include all responses rather than unique PINS

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#714]
<img width="593" alt="Bildschirmfoto 2019-10-25 um 11 00 48" src="https://user-images.githubusercontent.com/23721486/67558428-470f3c00-f717-11e9-9443-299f01aed270.png">

On Dashboard(s) there seem to be too many Participants. Please use only unique PINs as stored in Participant table...

**Comment by RamyAlshurafa** [comment]
@dupreesi 
I checked this and found the `Participants` are the count of the confirmed emails, not the PINs
