### ISSUE TITLE
Bug: No confirmed participants in reach section

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#715]
it says no confirmed participants for pre-course survey even though they are confirmed participants for the related sessions: http://www.clipular.com/posts/5092395027529728?k=r3a2SgklE19X3hgA-jYe9JVS3aw

please test...

**Comment by RamyAlshurafa** [comment]
can't replicate this

**Comment by dupreesi** [comment]
still appearing 
<img width="1034" alt="Bildschirmfoto 2019-11-12 um 08 05 18" src="https://user-images.githubusercontent.com/23721486/68653238-320e1780-0523-11ea-9747-598b0f71fdab.png">

**Comment by dupreesi** [comment]
@RamyAlshurafa I think the bug is only if you set up a session including pre-surveys. 
Can you please test: log in as trainer, set up session type 1, add 1 attendee, fill in pre- and post survey with same PIN. Then log in as same trainer and check results (reach). You should see that post survey has response rate whereas pre-survey does not. 
I think for me this was the case because the filterSessions query which is used by the getResponseRate helper doesn't pass on any confirmed emails for the first survey (pre-survey) so when you log the sessions object in getResponseRate you get 
```
[ { _id: '1',
[0]     sessions: 2,
[0]     key: 5dcbe13f59a46a4d4ea7c455,
[0]     participants: 24,
[0]     emails: [ [], [Array] ],
[0]     type: 'Session 1' } ]
```
so in emails the first array is empty... is that the bug @RamyAlshurafa ?
