### ISSUE TITLE
Please Test: Trainer Feedback Results

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#720]
I've filled in 1 response for a post-session (no other are being stored) and I'm getting the following allocation of percentages: 
<img width="482" alt="Bildschirmfoto 2019-10-27 um 19 12 11" src="https://user-images.githubusercontent.com/23721486/67639243-ce160d00-f8ed-11e9-9553-9d86b5829b40.png">
<img width="476" alt="Bildschirmfoto 2019-10-27 um 19 12 15" src="https://user-images.githubusercontent.com/23721486/67639244-d1a99400-f8ed-11e9-8a24-9cf4f14cb091.png">

shouldn't it be 100 % at the answer I've given?

**Comment by RamyAlshurafa** [comment]
![3](https://user-images.githubusercontent.com/34629478/67754252-ce71ed80-fa3e-11e9-911f-b67309d7cae6.png)
I'm not able to replicate this bug, can you go through it again and write the scenario that make this bug please

**Comment by RamyAlshurafa** [comment]
@dupreesi
