### ISSUE TITLE
Bug: Alter Gender Question

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#727]
In demographic section please update gender question like so

- male 
- female
- other 

for other don't create possibilty to specify ... just count as answer

**Comment by dupreesi** [comment]
pushed back for now due to a lot of changes required across app such as survey question and filtering functionalities. to be discussed

**Comment by dupreesi** [comment]
@RamyAlshurafa can you please try to create a 'other' option without further questions for this?

**Comment by RamyAlshurafa** [comment]
@dupreesi 
so will be the options in the picture you posted above except the last option to be 'other' without open input text
