### ISSUE TITLE
Bug: Internet Explorer 11 -> Cannot add new emails to list

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/connect5#743]
please see video -> tested using Browserling.com

https://www.loom.com/share/200ef2ee47444fdebffc5cc2e8e6a1b7

Seems to work fine on chrome etc..

**Comment by RamyAlshurafa** [comment]
Hey @dupreesi I tested that, and I got the same result as you got, but the DB has been updated
and if you closed the browser and opened it again you will see the new list, not sure what to do in this case, I think we can show them a warning message here to aware them that some functionalities may not work on IE, 
what do you think?

**Comment by dupreesi** [comment]
Yes very good idea! Thanks for checking. So show a warning message when using internet explorer?

Von meinem iPhone gesendet
